config/routes.rb
Rails.application.routes.draw do
  resources :vlogs do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vlog
end

app/models/vlog.rb
class Vlog < ApplicationRecord
    has_many :reviews
    validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/vlogs_controller.rb
class VlogsController < ApplicationController
  before_action :set_vlog, only: [:show, :edit, :update, :destroy]

  # GET /vlogs
  # GET /vlogs.json
  def index
    @vlogs = Vlog.all
  end

  # GET /vlogs/1
  # GET /vlogs/1.json
  def show
  end

  # GET /vlogs/new
  def new
    @vlog = Vlog.new
  end

  # GET /vlogs/1/edit
  def edit
  end

  # POST /vlogs
  # POST /vlogs.json
  def create
    @vlog = Vlog.new(vlog_params)

    respond_to do |format|
      if @vlog.save
        format.html { redirect_to @vlog, notice: 'Vlog was successfully created.' }
        format.json { render :show, status: :created, location: @vlog }
      else
        format.html { render :new }
        format.json { render json: @vlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vlogs/1
  # PATCH/PUT /vlogs/1.json
  def update
    respond_to do |format|
      if @vlog.update(vlog_params)
        format.html { redirect_to @vlog, notice: 'Vlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @vlog }
      else
        format.html { render :edit }
        format.json { render json: @vlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vlogs/1
  # DELETE /vlogs/1.json
  def destroy
    @vlog.destroy
    respond_to do |format|
      format.html { redirect_to vlogs_url, notice: 'Vlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vlog
      @vlog = Vlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vlog_params
      params.require(:vlog).permit(:title, :desc, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vlogs_helper.rb
module VlogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KidsVlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vlogs/_form.html.erb
<%= form_for(vlog) do |f| %>
  <% if vlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vlog.errors.count, "error") %> prohibited this vlog from being saved:</h2>

      <ul>
      <% vlog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vlogs/edit.html.erb
<h1>Editing Vlog</h1>

<%= render 'form', vlog: @vlog %>

<%= link_to 'Show', @vlog %> |
<%= link_to 'Back', vlogs_path %>

app/views/vlogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vlogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vlogs.each do |vlog| %>
      <tr>
        <td><%= vlog.title %></td>
        <td><%= vlog.desc %></td>
        <td><%= vlog.link %></td>
        <td><%= link_to 'Show', vlog %></td>
        <td><%= link_to 'Edit', edit_vlog_path(vlog) %></td>
        <td><%= link_to 'Destroy', vlog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vlog', new_vlog_path %>

app/views/vlogs/new.html.erb
<h1>New Vlog</h1>

<%= render 'form', vlog: @vlog %>

<%= link_to 'Back', vlogs_path %>

app/views/vlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vlog.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @vlog.desc %>
</p>

<p>
  <strong>Link:</strong>
  <%= @vlog.link %>
</p>

<%= link_to 'Edit', edit_vlog_path(@vlog) %> |
<%= link_to 'Back', vlogs_path %>

<br><br>

<h2> Reviews </h2>

  <div id="Reviews">
    <%# Expands to render partial: 'reviews/review', collection: @vlog.reviews %>
    <%= render @vlog.reviews %>
  </div>

  <% render 'reviews/new', vlog: @vlog %>
 </div>